export default {
  getTargetQuerySelector: (target: HTMLElement, query: string): HTMLElement => <HTMLElement>target.querySelector(query),
  body: (): HTMLElement => <HTMLElement>document.querySelector('body'),
  getCarElem: (): HTMLElement => <HTMLElement>document.querySelector('.car'),
  getRaceBtn: (): HTMLElement => <HTMLElement>document.querySelector('.button_race'),
  getGenerateBtn: (): HTMLElement => <HTMLElement>document.querySelector('.button_generate'),
  getResetBtn: (): HTMLElement => <HTMLElement>document.querySelector('.button_reset'),
  getBrandName: (): HTMLInputElement => <HTMLInputElement>document.querySelector('.brand__display_create'),
  getColorName: (): HTMLInputElement => <HTMLInputElement>document.querySelector('.color__input_create'),
  getCreateBtn: (): HTMLButtonElement => <HTMLButtonElement>document.querySelector('.color__button_create'),
  getPrevBtn: (): HTMLElement => <HTMLElement>document.querySelector('.page__but_prev'),
  getNextBtn: (): HTMLElement => <HTMLElement>document.querySelector('.page__but_next'),
  getUpdateBtn: (): HTMLButtonElement => <HTMLButtonElement>document.querySelector('.color__button_update'),
  getBrandNameUpdate: (): HTMLInputElement => <HTMLInputElement>document.querySelector('.brand__display_update'),
  getColorNameUpdate: (): HTMLInputElement => <HTMLInputElement>document.querySelector('.color__input_update'),
  getDriveBtn: (): HTMLElement => <HTMLElement>document.querySelector('.car__but_drive'),
  getStopBtn: (): HTMLElement => <HTMLElement>document.querySelector('.car__but_stop'),
  getGarage: (): HTMLElement => <HTMLElement>document.querySelector('.garage__cars'),
  getGarageTotalCount: (): HTMLElement => <HTMLElement>document.querySelector('.garage__total-count'),
  getGaragePagination: (): HTMLElement => <HTMLElement>document.querySelector('.garage__pagination'),
  getWinMessage: (): HTMLElement => <HTMLElement>document.querySelector('.win-message'),
  getWinners: (): HTMLElement => <HTMLElement>document.querySelector('.table__main'),
  getWinnersTotalCount: (): HTMLElement => <HTMLElement>document.querySelector('.winners__total-count'),
  getWinnersPagination: (): HTMLElement => <HTMLElement>document.querySelector('.winners__pagination'),
  getQuerySelector: (query: string): HTMLElement => <HTMLElement>document.querySelector(query),
  getQuerySelectorAll: (query: string): NodeListOf<HTMLElement> => document.querySelectorAll<HTMLElement>(query),
};
