export default {
  getTargetQuerySelector: (target: HTMLElement, query: string): HTMLElement | null =>
    target.querySelector<HTMLElement>(query),
  body: (): HTMLElement | null => document.querySelector<HTMLElement>('body'),
  getCarElem: (): HTMLElement | null => document.querySelector<HTMLElement>('.car'),
  getRaceBtn: (): HTMLElement | null => document.querySelector<HTMLElement>('.button_race'),
  getGenerateBtn: (): HTMLElement | null => document.querySelector<HTMLElement>('.button_generate'),
  getResetBtn: (): HTMLElement | null => document.querySelector<HTMLElement>('.button_reset'),
  getBrandName: (): HTMLInputElement | null => document.querySelector<HTMLInputElement>('.brand__display_create'),
  getColorName: (): HTMLInputElement | null => document.querySelector<HTMLInputElement>('.color__input_create'),
  getCreateBtn: (): HTMLButtonElement | null => document.querySelector<HTMLButtonElement>('.color__button_create'),
  getPrevBtn: (): HTMLElement | null => document.querySelector<HTMLElement>('.page__but_prev'),
  getNextBtn: (): HTMLElement | null => document.querySelector<HTMLElement>('.page__but_next'),
  getUpdateBtn: (): HTMLButtonElement | null => document.querySelector<HTMLButtonElement>('.color__button_update'),
  getBrandNameUpdate: (): HTMLInputElement | null => document.querySelector<HTMLInputElement>('.brand__display_update'),
  getColorNameUpdate: (): HTMLInputElement | null => document.querySelector<HTMLInputElement>('.color__input_update'),
  getDriveBtn: (): HTMLElement | null => document.querySelector<HTMLElement>('.car__but_drive'),
  getStopBtn: (): HTMLElement | null => document.querySelector<HTMLElement>('.car__but_stop'),
  getGarage: (): HTMLElement | null => document.querySelector<HTMLElement>('.garage__cars'),
  getGarageTotalCount: (): HTMLElement | null => document.querySelector<HTMLElement>('.garage__total-count'),
  getGaragePagination: (): HTMLElement | null => document.querySelector<HTMLElement>('.garage__pagination'),
  getWinMessage: (): HTMLElement | null => document.querySelector<HTMLElement>('.win-message'),
  getWinners: (): HTMLElement | null => document.querySelector<HTMLElement>('.table__main'),
  getWinnersTotalCount: (): HTMLElement | null => document.querySelector<HTMLElement>('.winners__total-count'),
  getWinnersPagination: (): HTMLElement | null => document.querySelector<HTMLElement>('.winners__pagination'),
  getQuerySelector: (query: string): HTMLElement | null => document.querySelector<HTMLElement>(query),
  getQuerySelectorAll: (query: string): NodeListOf<HTMLElement> | null => document.querySelectorAll<HTMLElement>(query),
};
